### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by YarikineZ** [jeromevonk/flask_face_detection#1]
Add the following buildpack:
https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt

and include a list of apt package names to be installed the Aptfile
____________________________________________________________________________________

Hi! Could you please help me with it?
I ve spend hours for implementing open cv to heroku, but haven't succeed with it.

Can we connect with skype/e-mail/telegram/whats-up?

**Comment by verra11** [comment]
Hey there!
I had the same problem with opencv on heroku. I kept getting the error:
"Import Error : libsm.so.6 ...... no such file or directory"
Something like that, and adding the apt-buildpack did not solve anything.

Finally, the issue was resolved when I provided "opencv-python-headless" instead of "opencv-python" as a requirement in my requirements.txt file.
Hope this helps!
